// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// No `migrations` block: this project has never had a prisma/migrations
// directory -- schema changes are applied with `prisma db push` (see
// docs/superpowers/specs/2026-08-21-leads-crm-unverified.md), unlike
// trip-scheduler which tracks real migrations.
export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
