// The webhook receiver as a plain function: the route hands it the request pieces and the real store, tests hand it fakes.
import type { DomainsIndex } from '@/content/resolve-rewrite'
import type { CityContent } from '@/content/types'
import { cityHref } from '@/content/interpolate'
import { cleanArticleHtml, excerptOf, plainText } from './html'
import { normalizeSlug, parseDelivery } from './payload'
import { cityKeyForDomain, domainForCity } from './resolve-city'
import { findDuplicate, type Candidate } from './similarity'
import type { BlogPostInput, BlogPostRecord } from './types'

export type ReceiveInput = {
  authorization: string | null
  body: unknown
  /** Host the delivery arrived on, for the live URL of a city with no domain yet. */
  host: string
}

export type ReceiveDeps = {
  expectedToken: string | null
  domains: DomainsIndex
  getCity: (key: string) => Promise<CityContent>
  upsertPost: (input: BlogPostInput) => Promise<BlogPostRecord>
  postBySlug: (cityKey: string, slug: string) => Promise<BlogPostRecord | null>
  candidatesOutside: (cityKey: string) => Promise<Candidate[]>
  revalidate: (paths: string[]) => void
}

export type ReceiveResult = { status: number; body: Record<string, unknown> }

export async function receiveDelivery(input: ReceiveInput, deps: ReceiveDeps): Promise<ReceiveResult> {
  if (deps.expectedToken === null || input.authorization !== `Bearer ${deps.expectedToken}`) {
    return { status: 401, body: { error: 'Unauthorized' } }
  }

  const parsed = parseDelivery(input.body)
  if (!parsed.ok) return { status: 400, body: { error: parsed.error } }
  const { delivery } = parsed

  if (delivery.test === true) return { status: 200, body: { ok: true, test: true } }

  const { article } = delivery
  const cityKey = cityKeyForDomain(delivery.website.domain, deps.domains)

  // site pages the tool designs (services, locations, pricing) are generated by our own pipeline: answer with the
  // page we already serve for that place, so the tool's "live" link lands somewhere real
  if (delivery.event !== 'article.published' || article.type !== 'post') {
    console.log(`blog webhook: skipped ${delivery.event} "${article.title}" (${delivery.website.domain})`)
    const url = cityKey === null ? null : await existingPageUrl(cityKey, article.slug, input.host, deps)
    return { status: 200, body: { ok: true, skipped: delivery.event, ...(url === null ? {} : { url }) } }
  }

  if (cityKey === null) {
    return { status: 422, body: { error: `unknown website domain "${delivery.website.domain}"; map it to a city first` } }
  }
  let city: CityContent
  try {
    city = await deps.getCity(cityKey)
  } catch {
    return { status: 422, body: { error: `no city content for "${cityKey}"` } }
  }

  const slug = normalizeSlug(article.slug)
  if (slug === null) return { status: 422, body: { error: `unusable slug "${article.slug}"` } }
  if (!article.content_html) return { status: 422, body: { error: 'content_html missing' } }

  const externalId = String(article.id)
  const existing = await deps.postBySlug(cityKey, slug)
  if (existing !== null && existing.externalId !== externalId) {
    return { status: 422, body: { error: `slug "${slug}" is already used by another post on this site` } }
  }

  const html = cleanArticleHtml(article.content_html, article.title, city)
  const text = plainText(html)
  const duplicate = findDuplicate(article.title, text, await deps.candidatesOutside(cityKey))
  if (duplicate !== null) {
    const { match, score } = duplicate
    return {
      status: 422,
      body: { error: `duplicate of ${match.cityKey}/${match.slug} (similarity ${score.toFixed(2)}); every site needs its own article` },
    }
  }

  const publishedAt = article.published_at ? new Date(article.published_at) : new Date()
  await deps.upsertPost({
    cityKey,
    externalId,
    slug,
    title: article.title,
    html,
    text,
    excerpt: excerptOf(html),
    metaTitle: article.seo?.title ?? null,
    metaDescription: article.seo?.meta_description ?? null,
    imageUrl: article.og_image_url ?? null,
    imageAlt: article.og_image_alt ?? null,
    categories: article.categories ?? [],
    tags: article.tags ?? [],
    publishedAt: Number.isNaN(publishedAt.getTime()) ? new Date() : publishedAt,
  })
  deps.revalidate([`/${cityKey}/blog`, `/${cityKey}/blog/${slug}`, '/sitemap.xml'])

  const url = liveUrl(cityKey, city, `/blog/${slug}`, input.host, deps.domains)
  console.log(`blog webhook: stored ${cityKey}/${slug}`)
  return { status: 200, body: { ok: true, url } }
}

// a mapped domain serves the city at its root; the shared host serves it under the city-key prefix
function liveUrl(cityKey: string, city: CityContent, path: string, host: string, domains: DomainsIndex): string {
  const domain = domainForCity(cityKey, domains)
  return domain ? `https://${domain}${path}` : `https://${host}${cityHref(city, path)}`
}

// the area page whose slug ends in the tool's page slug ("st-paul" -> /cleaning-service-st-paul), else the front page
async function existingPageUrl(cityKey: string, pageSlug: string, host: string, deps: ReceiveDeps): Promise<string | null> {
  let city: CityContent
  try {
    city = await deps.getCity(cityKey)
  } catch {
    return null
  }
  const slug = normalizeSlug(pageSlug)
  const area = slug === null ? undefined : city.research.suburbs.find((s) => s.slug === slug || s.slug.endsWith(`-${slug}`))
  const path = area && city.hasSuburbPages ? `/${area.slug}` : '/'
  return liveUrl(cityKey, city, path, host, deps.domains)
}
