// The webhook receiver as a plain function: the route hands it the request pieces and the real store, tests hand it fakes.
import type { DomainsIndex } from '@/content/resolve-rewrite'
import type { CityContent } from '@/content/types'
import { cityHref } from '@/content/interpolate'
import { cleanArticleHtml, excerptOf, plainText } from './html'
import { normalizeSlug, parseDelivery } from './payload'
import { cityKeyForDomain, domainForCity } from './resolve-city'
import { findDuplicate, type Candidate } from './similarity'
import type { BlogPostInput, BlogPostRecord } from './types'

export type ReceiveInput = {
  authorization: string | null
  body: unknown
  /** Host the delivery arrived on, for the live URL of a city with no domain yet. */
  host: string
}

export type ReceiveDeps = {
  expectedToken: string | null
  domains: DomainsIndex
  getCity: (key: string) => Promise<CityContent>
  upsertPost: (input: BlogPostInput) => Promise<BlogPostRecord>
  postBySlug: (cityKey: string, slug: string) => Promise<BlogPostRecord | null>
  candidatesOutside: (cityKey: string) => Promise<Candidate[]>
  revalidate: (paths: string[]) => void
}

export type ReceiveResult = { status: number; body: Record<string, unknown> }

export async function receiveDelivery(input: ReceiveInput, deps: ReceiveDeps): Promise<ReceiveResult> {
  if (deps.expectedToken === null || input.authorization !== `Bearer ${deps.expectedToken}`) {
    return { status: 401, body: { error: 'Unauthorized' } }
  }

  const parsed = parseDelivery(input.body)
  if (!parsed.ok) return { status: 400, body: { error: parsed.error } }
  const { delivery } = parsed

  if (delivery.test === true) return { status: 200, body: { ok: true, test: true } }

  // site pages the tool designs (services, locations, pricing) are generated by our own pipeline
  if (delivery.event !== 'article.published' || delivery.article.type !== 'post') {
    return { status: 200, body: { ok: true, skipped: delivery.event } }
  }

  const cityKey = cityKeyForDomain(delivery.website.domain, deps.domains)
  if (cityKey === null) {
    return { status: 422, body: { error: `unknown website domain "${delivery.website.domain}"; map it to a city first` } }
  }
  let city: CityContent
  try {
    city = await deps.getCity(cityKey)
  } catch {
    return { status: 422, body: { error: `no city content for "${cityKey}"` } }
  }

  const { article } = delivery
  const slug = normalizeSlug(article.slug)
  if (slug === null) return { status: 422, body: { error: `unusable slug "${article.slug}"` } }
  if (!article.content_html) return { status: 422, body: { error: 'content_html missing' } }

  const externalId = String(article.id)
  const existing = await deps.postBySlug(cityKey, slug)
  if (existing !== null && existing.externalId !== externalId) {
    return { status: 422, body: { error: `slug "${slug}" is already used by another post on this site` } }
  }

  const html = cleanArticleHtml(article.content_html, article.title, city)
  const text = plainText(html)
  const duplicate = findDuplicate(article.title, text, await deps.candidatesOutside(cityKey))
  if (duplicate !== null) {
    const { match, score } = duplicate
    return {
      status: 422,
      body: { error: `duplicate of ${match.cityKey}/${match.slug} (similarity ${score.toFixed(2)}); every site needs its own article` },
    }
  }

  const publishedAt = article.published_at ? new Date(article.published_at) : new Date()
  await deps.upsertPost({
    cityKey,
    externalId,
    slug,
    title: article.title,
    html,
    text,
    excerpt: excerptOf(html),
    metaTitle: article.seo?.title ?? null,
    metaDescription: article.seo?.meta_description ?? null,
    imageUrl: article.og_image_url ?? null,
    imageAlt: article.og_image_alt ?? null,
    categories: article.categories ?? [],
    tags: article.tags ?? [],
    publishedAt: Number.isNaN(publishedAt.getTime()) ? new Date() : publishedAt,
  })
  deps.revalidate([`/${cityKey}/blog`, `/${cityKey}/blog/${slug}`, '/sitemap.xml'])

  const domain = domainForCity(cityKey, deps.domains)
  const url = domain ? `https://${domain}/blog/${slug}` : `https://${input.host}${cityHref(city, `/blog/${slug}`)}`
  return { status: 200, body: { ok: true, url } }
}
